### ISSUE TITLE
About static analysis of 64-bit binaries

### ISSUE THREAD

**Issue by sikoushixinyou** [OSUSecLab/SelectiveTaint#2]
Hi！Thanks for taking the time to look at my issues.
About static.py,whether it can only analyze 32-bit binary files, but not 64-bit binary？
When I use it to analyze 64-bit binaries(eg.df,ls), python reports the following error:
Traceback (most recent call last):
  File "static.py", line 7692, in <module>
    main()
  File "static.py", line 7604, in main
    readelf_sections_info()
  File "static.py", line 6878, in readelf_sections_info
    info.sectionsinfo.append([restline1[0], restline1[1], int(restline1[2], 16), int(restline1[3], 16), int(restline1[4], 16)])
IndexError: list index out of range

Is it possible to modify the code(static.py) so that it can analyze 64-bit binary, and is it very difficult to complete this work?

**Comment by jjang3** [comment]
I just wanted to echo this problem as well as shown below image. Does this work only support 32-bit binary files? It would be helpful to know if this is just an inherent limitation or if it is a bug that can be fixed by changing the code.

![image](https://user-images.githubusercontent.com/42549923/200662071-6f6ddeb2-ab9b-4cb5-a4ff-73aaf0bc2d56.png)

Thank you in advance.
